# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54af4756cc70ca293f6b91e16b8a27f2631919f1ba8dbc6e7a17df0c77fe35939487b195895e7a8c1c08f6e2249983f37ccfc10e450ad11ac70859a374788678

test:
  secret_key_base: f0cd073332d5831851811a0fbd27427676f12f730e0603e66c90d6a79df2ef454d9e44d4093b9863f4e6a22e8ddba443aeaddc3d38f885cac8087093ca445938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
